// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ast = require("./Ast.bs.js");
var Lexer = require("./Lexer.bs.js");
var Token = require("./Token.bs.js");
var Parser = require("./Parser.bs.js");
var Generator = require("./Generator.bs.js");

var program_text = "\n  int main(){ return 2;}\n  ";

Generator.generate_code(Ast.printAST(Parser.parse_program(Token.printTokenList(Lexer.lex(program_text)))));

exports.program_text = program_text;
/*  Not a pure module */
