// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function tradu(t) {
  switch (t) {
    case "Addition" :
        return "add";
    case "Bitwise" :
        return "not";
    case "Division" :
        return "div";
    case "Multiplication" :
        return "mul";
    case "Negation" :
        return "neg";
    case "ReturnKeyword" :
        return "ret";
    default:
      throw {
            RE_EXN_ID: "Match_failure",
            _1: [
              "Words.re",
              1,
              26
            ],
            Error: new Error()
          };
  }
}

function registro(n) {
  switch (n) {
    case 0 :
        return "%eax";
    case 1 :
        return "%ebx";
    case 2 :
        return "%ecx";
    case 3 :
        return "%edx";
    default:
      throw {
            RE_EXN_ID: "Match_failure",
            _1: [
              "Words.re",
              12,
              27
            ],
            Error: new Error()
          };
  }
}

exports.tradu = tradu;
exports.registro = registro;
/* No side effect */
